
name: 'jaffle_shop'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'
source-paths: ["models", "sources"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

vars:
  customers_catalog: customersdb
  customers_schema: public
  orders_catalog: ordersdb
  orders_schema: public
  payments_catalog: paymentsdb
  payments_schema: public

models:
  jaffle_shop:
      materialized: table
      staging:
        materialized: view
